# Generated by Django 3.2.5 on 2021-10-14 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Poland', 'Polska'), ('USA', 'Stany Zjednoczone Ameryki'), ('France', 'Francja'), ('Russia', 'Rosja')], max_length=50)),
                ('category', models.CharField(choices=[('circulation coin', 'moneta obiegowa'), ('commemorative coin', 'moneta okolicznościowa'), ('collector coin', 'moneta kolekcjonerska')], max_length=50)),
                ('year_first', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1865)])),
                ('year_last', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1865)])),
                ('silver_purity', models.IntegerField(choices=[(0.999, '0.999'), (0.925, '0.925'), (0.9, '0.900'), (0.835, '0.835'), (0.75, '0.750'), (0.68, '0.680'), (0.625, '0.625')])),
            ],
        ),
    ]
