# Generated by Django 2.2.24 on 2021-10-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20211014_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
