# Generated by Django 2.2.24 on 2021-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20211014_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='silver_purity',
            field=models.DecimalField(choices=[(0.999, '0.999'), (0.925, '0.925'), (0.9, '0.900'), (0.835, '0.835'), (0.75, '0.750'), (0.68, '0.680'), (0.625, '0.625')], decimal_places=3, max_digits=4),
        ),
    ]
