# Generated by Django 2.2.24 on 2021-10-14 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20211014_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='silver_purity',
            field=models.DecimalField(choices=[(Decimal('0.999'), '0.999'), (Decimal('0.925'), '0.925'), (Decimal('0.900'), '0.900'), (Decimal('0.835'), '0.835'), (Decimal('0.750'), '0.750'), (Decimal('0.680'), '0.680'), (Decimal('0.625'), '0.625')], decimal_places=3, max_digits=4),
        ),
    ]
