# Generated by Django 2.2.24 on 2021-10-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20211014_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot', models.DecimalField(decimal_places=15, max_digits=17)),
                ('data', models.CharField(max_length=10)),
            ],
        ),
    ]
