# Generated by Django 2.2.24 on 2021-10-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20211018_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silverspot',
            old_name='data',
            new_name='price_data',
        ),
    ]
