# Generated by Django 2.2.24 on 2021-10-21 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20211018_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
