# Generated by Django 2.2.24 on 2021-10-21 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_coin_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
